
INSERT INTO products
(
    title,
    description,
    excerpt,
    image,
    price,
    category_id,
    preparing_time,
    calories,
    total_sales,
    servings
) VALUES
(
    'BBQ Chicken Pizza',
    'Loaded with all-white-meat chicken, bacon, fresh onions, green peppers, and mozzarella and cheddar cheese',
    'Loaded with all-white-meat chicken, bacon...',
    'bbq_chicken_pizza.jpg',
    20.99,
    1,
    20,
    '260 calories per slice',
    240,
    2
),
(
    "Buffalo Chicken Wings",
    "Buffalo Chicken Recipe is a delicious weeknight meal that utilizes just a handful of simple ingredients, such as chicken breasts, hot sauce, honey, garlic, and butter  ",
    "Buffalo Chicken Recipe is a delicious weeknight...",
    "buffalo_chicken_wings.jpg",
    7.99,
    4,
    30,
    "232 calories per serving",
    500,
    1
),
(
    "Chicken Bites",
    "A juicy piece of chicken with all white meat served with a sauce of your choice.",
    "A juicy piece of chicken with all...",
    "chicken_bites.jpg",
    10.99,
    4,
    15,
    "260 calories per 100gm",
    350,
    1
),
(
    "Creamy Garlic Pizza",
    "Every bite is bursting with delicious creamy garlic flavor, beginning with the garlic sauce base, a six-cheese blend, and the parmesan cheese on top.",
    "Every bite is bursting with delicious creamy...",
    "creamy_garlic_pizza.jpg",
    13.99,
    1,
    20,
    "260 calories per slice",
    327,
    2
),
(
    "Italian Classic Pizza",
    "Italian sausage, pepperoni, chopped mushroom, roasted red pepper and pizza mozzarella.",
    "Italian sausage, pepperoni, chopped...",
    "italian_classic_pizza.jpg",
    5,
    1,
    15,
    "246 calories per 100gm",
    238,
    2
),
(
    "Farm House Pizza",
    "Italian sausage, crispy corn, chopped mushroom, roasted red pepper, cheddar cheese and pizza mozzarella.",
    "Italian sausage, crispy corn, chopped...",
    "farm_house_pizza.jpg",
    13.99,
    1,
    15,
    "230 calories per slice",
    102,
    2
),
(
    "Garlic Bread Combo",
    "A blend of cheddar and mozzarella cheeses baked to perfection. With marinara sauce.",
    "A blend of cheddar and mozzarella...",
    "garlic_bread_combo.jpg",
    9.99,
    4,
    15,
    "150 calories per 100gm",
    218,
    1
),
(
    "Fat boy cheese burger",
    "Made with four 100% Canadian beef patties, special sauce, crisp lettuce, processed cheddar cheese, pickles, onions and hickory-smoked bacon strips on a toasted sesame seed bun.",
    "Made with four 100% Canadian beef...",
    "fat_boy_cheese_burger.jpg",
    9.99,
    5,
    20,
    "220 calories per 100gm",
    434,
    1
),
(
    "Spicy Potato Soft Taco",
    "Made with soft tortilla filled with spicy roasted potato with maxican cheese.",
    "Made with soft tortilla filled ...",
    "spicy_potato_soft_taco.jpg",
    2.99,
    4,
    3,
    "140 calories per 100gm",
    437,
    1
),
(
    "Crunch Wrap Supreme",
    "Wrap made with crunchy corn tortilla, lettuce, tomatoes and cream cheese.",
    "Wrap made with crunchy corn tortilla...",
    "crunch_wrap_supreme.jpg",
    4.99,
    4,
    15,
    "220 calories per 100gm",
    434,
    1
),
(
    "Choco Lava Cake",
    "Oven baked chocolate cakes, crunchy on the outside with molten chocolate on the inside.",
    "Oven baked chocolate cakes...",
    "choco_lava_cake.jpg",
    20.99,
    3,
    20,
    "260 calories per slice",
    240,
    2
),
(
    "Chicken Wings",
    "Buffalo Chicken Recipe is a delicious weeknight meal that utilizes just a handful of simple ingredients, such as chicken breasts, hot sauce, honey, garlic, and butter  ",
    "Buffalo Chicken Recipe is a delicious weeknight...",
    "chicken_wings.jpg",
    6.99,
    4,
    26,
    "256 calories per serving",
    568,
    1
),
(
    "Spicy Chicken Nuggets",
    "A juicy piece of chicken with all white meat served with a sauce of your choice.",
    "A juicy piece of chicken with all...",
    "spicy_chicken_nuggets.jpg",
    11.99,
    4,
    20,
    "232 calories per 100gm",
    350,
    1
),
(
    "Cheesy Garlic Pizza",
    "Every bite is bursting with delicious cheesy garlic flavor, beginning with the garlic sauce base, a six-cheese blend, and the parmesan cheese on top.",
    "Every bite is bursting with delicious cheesy...",
    "cheesy_garlic_pizza.jpg",
    12.99,
    1,
    20,
    "256 calories per slice",
    646,
    2
),
(
    "Chicken Caesar Wrap",
    "Italian sausage, pepperoni, chopped mushroom, roasted red pepper and pizza mozzarella.",
    "Italian sausage, pepperoni, chopped...",
    "chicken_caesar_wrap.jpg",
    5,
    4,
    15,
    "246 calories per 100gm",
    238,
    1
),
(
    "Hot Fudge Sundae",
    "Italian sausage, crispy corn, chopped mushroom, roasted red pepper, cheddar cheese and pizza mozzarella.",
    "Italian sausage, crispy corn, chopped...",
    "hot_fudge_sundae.jpg",
    5.99,
    3,
    5,
    "267 calories per 50gm",
    263,
    1
),
(
    "Quarter Pounder with Cheese",
    "A blend of cheddar and mozzarella cheeses baked to perfection. With marinara sauce.",
    "A blend of cheddar and mozzarella...",
    "quarter_pounder_with_cheese.jpg",
    7.99,
    5,
    15,
    "362 calories per 100gm",
    218,
    1
),
(
    "Double cheese burger",
    "Made with four 100% Canadian beef patties, special sauce, crisp lettuce, processed cheddar cheese, pickles, onions and hickory-smoked bacon strips on a toasted sesame seed bun.",
    "Made with four 100% Canadian beef...",
    "double_cheese_burger.jpg",
    10.99,
    5,
    15,
    "247 calories per 100gm",
    567,
    1
),
(
    "Double Scoop Cone",
    "Made with soft tortilla filled with spicy roasted potato with maxican cheese.",
    "Made with soft tortilla filled ...",
    "double_scoop_cone.jpeg",
    4.99,
    3,
    3,
    "240 calories per 100gm",
    632,
    1
),
(
    "Strawberry Fruitopia",
    "Wrap made with crunchy corn tortilla, lettuce, tomatoes and cream cheese.",
    "Wrap made with crunchy corn tortilla...",
    "strawberry_fruitopia.jpg",
    2.99,
    2,
    5,
    "284 calories per serving",
    1321,
    1
);